import json
import os
import re
import torch
import argparse
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM

from history import History
from message import Message
from roles import Roles
from qwen_baseline import QwenTeacher
from llm_judge import judge_conversation

MODEL_PATH = "./models/Qwen_SFT_model/finetuned_weighted_qwen_instruct_teacher_model"
TRAIN_OUT = "./data/preference-data-no-real-teacher/train.jsonl"
EVAL_OUT = "./data/preference-data-no-real-teacher/eval.jsonl"


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--num_generations', type=int, default=5, help='Number of generations per teacher turn')
    return parser.parse_args()


def parse_conversation(conversation_str):
    '''Parse the conversation string into a list of (speaker, turn_text) tuples.

    conversationample:
    [
        ("Teacher","Hi ..."),
        ("Student","I got 72 ..."),
        ("Teacher","...")
    ]
    
    '''
    turns = []
    for turn in conversation_str.split("|EOM|"):
        turn = turn.strip() # remove whitespace
        if not turn or ": " not in turn:
            print(f"Improper formatting, skipping turn. Should not happen: '{turn}'")
            continue
        speaker, turn_text = turn.split(": ", 1) # split string into these two parts to format into tuple
        turns.append((speaker.strip(), turn_text.strip()))
    return turns


def clean_response(turn_text):
    '''
    Clean the teacher response turn_text generated by LLM by removing any leading "Teacher:" or "Assistant:" and trailing content after the nconversationt speaker or end-of-message token.
    '''
    turn_text = turn_text.strip()
    turn_text = re.sub(r"^\s*(Teacher|Assistant):\s*", "", turn_text)
    turn_text = re.split(r"\nTeacher:|\nStudent:|\nAssistant:|\nUser:|\|EOM\|", turn_text)[0].strip()
    return turn_text

def build_rows(dataset):
    '''
    Build preference pairs from the dataset
    Each row is a dict with keys "prompt", "chosen", and "rejected"
    '''
    rows = []

    for conversation in dataset:
        question = conversation["question"]
        solution = conversation["ground_truth"]
        turns = parse_conversation(conversation["conversation"])
        history = History()

        for speaker, turn_text in turns:
            if speaker.lower() == "teacher":
                if history.messages and history.messages[-1].persona == Roles.STUDENT:
                    prompt = teacher.build_prompt(history, question, solution)
                    # chosen = turn_text.strip()
                    responses = []
                    for _ in range(NUMBER_OF_GENERATIONS):
                        responses.append(clean_response(teacher.response(history, question, solution))) # in case of formatting issues in dataset

                    # Compare between every pair of generated responses (N*(N-1)/2)
                    for i in range(len(responses)):
                        for j in range(i + 1, len(responses)):
                            # llm as a judge
                            score_one = judge_conversation(model, tokenizer, device, question, solution, history.format() + f"\nTeacher: {responses[i]}")
                            score_two = judge_conversation(model, tokenizer, device, question, solution, history.format() + f"\nTeacher: {responses[j]}")

                            # Compare scores on average across dimensions, but weight "overall_quality" more heavily since it's a holistic judgment
                            avg_score_one = (score_one["overall_quality"] * 2 + score_one["socratic"] * 1.5 + score_one["accuracy"] + score_one["relevance"] + score_one["conciseness"]) / 6.5
                            avg_score_two = (score_two["overall_quality"] * 2 + score_two["socratic"] * 1.5 + score_two["accuracy"] + score_two["relevance"] + score_two["conciseness"]) / 6.5
                            if avg_score_one > avg_score_two:
                                chosen, rejected = responses[i], responses[j]
                            else:
                                chosen, rejected = responses[j], responses[i]

                            if chosen and rejected and chosen != rejected:
                                rows.append({
                                    "prompt": prompt,
                                    "chosen": chosen,
                                    "rejected": rejected
                                })

                history.add_message(Message(Roles.TEACHER, turn_text.strip()))

            else:
                history.add_message(Message(Roles.STUDENT, turn_text.strip()))
    return rows

def write_jsonl(path, rows):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Loading checkpoint:", MODEL_PATH)
tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
model = AutoModelForCausalLM.from_pretrained(MODEL_PATH).to(device)
model.eval()

if __name__ == "__main__":
    args = parse_args()
    NUMBER_OF_GENERATIONS = args.num_generations

    teacher = QwenTeacher(model, tokenizer, device)
    dataset = load_dataset("eth-nlped/mathdial")

    train_rows = build_rows(dataset["train"])
    eval_rows = build_rows(dataset["test"])

    write_jsonl(TRAIN_OUT, train_rows)
    write_jsonl(EVAL_OUT, eval_rows)

    print(f"Wrote {len(train_rows)} rows to {TRAIN_OUT}")
    print(f"Wrote {len(eval_rows)} rows to {EVAL_OUT}")
