import json
import os
import re
import sys
import torch

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "interactivetutoring"))

from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM

from history import History
from message import Message
from roles import Roles
from qwen_baseline import QwenTeacher

MODEL_PATH = "./models/Qwen_SFT_model/finetuned_weighted_qwen_instruct_teacher_model"
TRAIN_OUT = "./data/preference-data/train.jsonl"
EVAL_OUT = "./data/preference-data/eval.jsonl"


def parse_conversation(conversation_str):
    '''Parse the conversation string into a list of (speaker, turn_text) tuples.

    conversationample:
    [
        ("Teacher","Hi ..."),
        ("Student","I got 72 ..."),
        ("Teacher","...")
    ]
    
    '''
    turns = []
    for turn in conversation_str.split("|EOM|"):
        turn = turn.strip() # remove whitespace
        if not turn or ": " not in turn:
            print(f"Improper formatting, skipping turn. Should not happen: '{turn}'")
            continue
        speaker, turn_text = turn.split(": ", 1) # split string into these two parts to format into tuple
        turns.append((speaker.strip(), turn_text.strip()))
    return turns


def clean_response(turn_text):
    '''
    Clean the teacher response turn_text generated by LLM by removing any leading "Teacher:" or "Assistant:" and trailing content after the nconversationt speaker or end-of-message token.
    '''
    turn_text = turn_text.strip()
    turn_text = re.sub(r"^\s*(Teacher|Assistant):\s*", "", turn_text)
    turn_text = re.split(r"\nTeacher:|\nStudent:|\nAssistant:|\nUser:|\|EOM\|", turn_text)[0].strip()
    return turn_text

def build_rows(dataset):
    '''
    Build preference pairs from the dataset
    Each row is a dict with keys "prompt", "chosen", and "rejected"
    '''
    rows = []

    for conversation in dataset:
        question = conversation["question"]
        solution = conversation["ground_truth"]
        turns = parse_conversation(conversation["conversation"])
        history = History()

        for speaker, turn_text in turns:
            if speaker.lower() == "teacher":
                if history.messages and history.messages[-1].persona == Roles.STUDENT:
                    prompt = teacher.build_prompt(history, question, solution)
                    chosen = turn_text.strip()
                    rejected = clean_response(teacher.response(history, question, solution)) # in case LLM malforms output

                    if chosen and rejected and chosen != rejected:
                        rows.append({
                            "prompt": prompt,
                            "chosen": chosen,
                            "rejected": rejected
                        })

                history.add_message(Message(Roles.TEACHER, turn_text.strip()))

            else:
                history.add_message(Message(Roles.STUDENT, turn_text.strip()))
    return rows

def write_jsonl(path, rows):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Loading checkpoint:", MODEL_PATH)
tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
model = AutoModelForCausalLM.from_pretrained(MODEL_PATH).to(device)
model.eval()

print("Building teacher...")
teacher = QwenTeacher(model, tokenizer, device)
print("Processing dataset and building preference pairs...")
dataset = load_dataset("eth-nlped/mathdial")

train_rows = build_rows(dataset["train"])
eval_rows = build_rows(dataset["test"])

write_jsonl(TRAIN_OUT, train_rows)
write_jsonl(EVAL_OUT, eval_rows)

print(f"Wrote {len(train_rows)} rows to {TRAIN_OUT}")
print(f"Wrote {len(eval_rows)} rows to {EVAL_OUT}")